### ISSUE TITLE
[Algorithm] 블록 구조체 만들기

### ISSUE THREAD

**Issue by seonghee2** [veryear/2048#14]
* [x] 내용: 데이터 값 (~18.08.29)

**Comment by fpdjsns** [comment]
개발하다가 8/18 까지 못 끝낼 것 같으면 개발일정 다시 산정해서 comment 달아주세요.

**Comment by seonghee2** [comment]
18일이 아니라 28일이었네요.

**Comment by seonghee2** [comment]
테스트 할 것이 있어
28일에서 29일로 변경합니다.

**Comment by fpdjsns** [comment]
했으면 이슈 체크박스에서 체크해주세영.

**Comment by seonghee2** [comment]
네!!
