### ISSUE TITLE
master 브랜치에 .idea 폴더가 있음.

### ISSUE THREAD

**Issue by fpdjsns** [veryear/2048#16]
test 파일 master 브랜치에 올린거 삭제하면서 .idea 폴더는 삭제안된 듯.
마스터 브랜치에서 .idea 폴더 삭제부탁드립니다.

**Comment by fpdjsns** [comment]
@seonghee2 
삭제하신 뒤에 해당 이슈에 코멘트 달고 이슈 클로즈 해주세요.
.idea폴더 있으면 gitignore 제대로 안먹을 수도 있어서 삭제해두는게 좋을 것 같습니다.

**Comment by seonghee2** [comment]
제 로컬상에서 삭제하라는 건가요?
origin에서 삭제하라는 건가요?

**Comment by fpdjsns** [comment]
로컬은 상관이 없는데 gitignore파일이 없는 원격 브랜치에는 .idea 있으면 안될듯.

**Comment by fpdjsns** [comment]
해당 이슈는 삭제하시고 PR 필요없이 마스터에 반영해주세영.

**Comment by seonghee2** [comment]
예!!

**Comment by fpdjsns** [comment]
마스터에 반영안됐는데 왜 닫으셨죠..?
문제 해결되면 닫아주세요.

**Comment by fpdjsns** [comment]
확인 완료 했습니다.
이슈 종료합니다.
다음부터는 이슈 완료하시면 곧바로 종료해주세요.
