### ISSUE TITLE
[UI/UX] 방향키 입력받기

### ISSUE THREAD

**Issue by seonghee2** [veryear/2048#17]
* [x] : 키보드 방향키 입력받아 리턴 
(상:Up, 우:Right, 하:Down, 좌:Left)
* [x] : 해당 방향으로 블럭 움직인 뒤의 모습 출력

**Comment by fpdjsns** [comment]
개발 중 태그 만들었습니다. 현재 개발 중인거는 이 태그 붙여주세요.
이슈가 많아서 뭐 개발 중인지 한 눈에 보기 힘들어서 추가했습니다~

**Comment by seonghee2** [comment]
네 알겠습니다.

**Comment by fpdjsns** [comment]
이거 벌써 개발 들어갔나요? 
생각해보니까 키보드 방향키 입력받는건 UX 부분 같은데, 제가 개발할까요?

**Comment by seonghee2** [comment]
코드 구현해놓긴했는데
집에서 올릴려고 해죠~
가져가시려면 가져가도 되심

**Comment by fpdjsns** [comment]
구현했으면 굳이 내가 가져갈필욘 없지.ㅎㅎ

**Comment by seonghee2** [comment]
ㅋㅋㅋㅋ엄청 간단해서~
네다섯줄 정도 나오는거 같아
암튼 오키!!

**Comment by fpdjsns** [comment]
옹옹 집가서 풀리퀘 날려줭.
다음에 플랫폼 바뀔때 입력받는거 개발은 내가할겜

**Comment by seonghee2** [comment]
얍얍!!

**Comment by seonghee2** [comment]
기간 하루만 더 늘리겠습니다.
죄송합니다.
자꾸 ㅎㅔ매네요

**Comment by seonghee2** [comment]
```python
from msvcrt import getch

def right():
	print('right')
	
def left():
	print('left')
	
def up():
	print('up')

def down():
	print('down')

key = ord(getch())	#input arrow keys

if key == 77:	#right arrow
	right
elif key == 75:	#left arrow
	left()
elif key == 72:	#up arrow
	up()
elif key == 80:	#down arrow
	down()
```

**Comment by seonghee2** [comment]
도저히 왜 안되는지 이유를 못찾겠습니다.
조금만 도와주시겠어요??

**Comment by seonghee2** [comment]
아직 while문은 넣지않았습니다.

**Comment by fpdjsns** [comment]
\`\`\` 
소스코드 
\`\`\`

```
예시
```

바꿔주세요. 이뿌겡. 보기좋겡

**Comment by fpdjsns** [comment]
파이썬은 들여쓰기가 생명인데..!

**Comment by seonghee2** [comment]
오호!
예

**Comment by fpdjsns** [comment]
해당 브랜치 푸시해두세요. Pr은 날리지마시구.
퇴근하고 한번볼게요

**Comment by seonghee2** [comment]
넵넵
집가서 브랜치 푸시해두겠습니다.

**Comment by fpdjsns** [comment]
근데 right에 괄호 빠졌네요. 복붙하면서 빠진거?

**Comment by fpdjsns** [comment]
그리고 한가지 더 꿀팁
\`\`\`python
소스코드
\`\`\`
이런식으로 적으면 파이썬 코드 하이라이트 적용되서 나옴.

```python
def right():
	print('right')
```
이런식으로.
위에 덧글은 제가 바꿔놨어요.
다음부턴 잘 활용해주세용.허헣

**Comment by seonghee2** [comment]
네넵!!!
복붙하면서 빠진 것 같네요

**Comment by seonghee2** [comment]
코드까지 넣어서 푸시 했는데 pr날리지 마요??

**Comment by fpdjsns** [comment]
돌아가면 pr 날리는데 안돌아간다면서용

**Comment by seonghee2** [comment]
아 예ㅋㅋㅋㅋㅋ

**Comment by fpdjsns** [comment]
다음에는 브랜치 푸시하면 이름도 알려주세용.

**Comment by seonghee2** [comment]
옙 알겠습니당~

**Comment by fpdjsns** [comment]
이거 테스트 어떻게 해요?> 인식되는지 안되는지 몰겄는데

**Comment by seonghee2** [comment]
어?왜 알림이 안왔네요?다시 설정했었는데...
입력값 넣으면 방향키 해당문자가 나오는 걸로 아는데
저두 그게 안되네요ㅠㅠ

**Comment by seonghee2** [comment]
그전에는 콘솔창에서 값치면 바로 나왔는데 계속  running만 되고 값이 나오지를 않아요 저는

**Comment by fpdjsns** [comment]
그럼 콘솔창에서 값치면 되던 코드도 좀 올려주세요 커멘트로. 비교해봐야할듯. 아예안되니 원인도 몰겠네요

**Comment by seonghee2** [comment]
저기서 말하는 그전은 블록 클래스만들때 말하는 거였습니다.
방향키는 계속해서 에러만 났었습니다.

**Comment by fpdjsns** [comment]
이거 담당자 저한테 넘겨주세요.
제가 하겠습니다.

**Comment by seonghee2** [comment]
네 이렇게 넘겨주는거 맞나요???

**Comment by fpdjsns** [comment]
네. 다른거 먼저 개발하고 하겠습니다.
다른 이슈 개발일정 산정해주시고 시작하시면 됩니다.

**Comment by seonghee2** [comment]
네 알겠습니다.
감사합니다!!

**Comment by fpdjsns** [comment]
개발일정 : 9/11 ~ 9/20 (10D)

**Comment by fpdjsns** [comment]
@seonghee2 
다른 이슈 개발일정 산정해주세요.
지금 못하면 언제부터 언제까지 하겠다. 
이정도라도 적어야 제가 언제 진행되는지 알죵.

**Comment by fpdjsns** [comment]
@seonghee2 
닫힌 이슈말고 여기에서 이야기해주세요.
오늘까지 개발일정이던 이슈가 있나요?
해당 이슈 개발중 태그 달아주세요.
개발중 태그는 진행중인 이슈도 포함되지만 다음에 개발하는 이슈도 해당 태그 달아두는게 맞는 것 같습니다.
다음에는 이걸 최우선으로 개발하겠다. 이런 의미로.
그래야 이슈에서 개발중태그보고 상대방의 일정을 파악할 수 있으니까요.

**Comment by seonghee2** [comment]
#15ㄱㅏ 오늘까지입니다.
아하 그러면 개발중태그 달아놓겠습니다.
