### ISSUE TITLE
개발 전 기능 분담 논의 필요

### ISSUE THREAD

**Issue by fpdjsns** [veryear/2048#2]
기능에 대해서 누가 어느 부분을 개발할지에 대해 논의가 필요하다고 생각합니다.

제가 생각해봤는데 크게 기능을 2부분으로 나눌 수 있을 것 같습니다.
1. UI, UX 
2. 게임 알고리즘 구현
이렇게 나누면 그나마 코드 충돌이 덜 발생하지 않을까용?

혹은 프로토타입형으로 기능을 잘게 나눠서 개발하고 싶은 부분 개발 후 merge 하면  issue에 올라온 기능들 중 개발하고 싶은 부분을 골라서 개발해도 좋다고 봅니다.
개발 인원이 많다면 이 개발방법은 비효율적이겠지만 2명이고 처음 파이썬을 써보는 입장에서 원하는 부분을 골고루 해볼수 있지 않을까요? 의사소통도 2명이라 비교적 빠르게 할 수 있고요.

두 방법 모두 개발 시작 전에 기능들을 이슈로 저장해두고 개발하면서 필요하다고 생각하는 부분들을 이슈에 꾸준히 등록해야 할 것 같습니다.

**Comment by fpdjsns** [comment]
생각난게 있어서 추가로 적습니다.
첫번째로 크게 기능을 2가지로 나누는 부분은 자기 담당이 정해져있으므로 개발 속도가 빠를 것 같습니다. (자신이 사용하고 싶은 기술을 곧바로 적용 가능하므로)
두 번째 같은 경우는 원하는 부분을 개발 가능하지만 선행적으로 개발이 이루어져야 하는 태스크들이 많을 것이라 예상됩니다. 예를 들어 블럭에 대한 클래스가 생성되어야 블럭을 움직이는 기능을 개발할 수 있는 것처럼 말입니다.

그래서 생각난 또 다른 기능 분담 방법은 다음과 같습니다.
처음 기획 단계에서 버전 1의 기능 범위를 최소화 시킵니다. 그러면 스펙아웃된 기능(버전 1 이후 버전에 추가될 기능)들이 나올 것입니다.
처음에는 일단 첫번째 방법 처럼 크게 두 부분으로 나누고 각자의 맡은 부분을 개발합니다. (개발하면서도 추가로 개발하고 싶은 기능들은 이슈에 등록합니다.) 원하고자 하는 기능들을 모두 개발 완료했을 때 master 브랜치로 버전 1.0을 머지합니다.
이 후에는 두번째 방법처럼 추가로 구현할 기능들(이슈에 등록되어 있음)을 하나씩 가져가서 개발합니다.
버전 1에서 뼈대를 크게 잡아뒀으므로 앞에서말한 선행으로 필요한 기능들이 많이 줄어들 것입니다.

즉,  버전 1(최대한 개발 범위 축소)까지는 방법 1적용. 이후 추가 기능은 방법 2 적용.

이 방법에 대해서는 어떻게 생각하쉽니까?

**Comment by seonghee2** [comment]
네 마직막에 말한 방법이 좋은 것 같습니다.

**Comment by fpdjsns** [comment]
그럼 간략하게 1, 2번 중에 누가 뭐할지 정할까요?
그 다음에 회의 한 번 해서 버전 1 스펙 정한다음에 wiki에 회의 내용 정리하고,
이슈에 각자 맡은거 알아서 등록해서 개발 진행하는 걸로 할까요?

**Comment by fpdjsns** [comment]
저는 기능 1번 UI, UX 해보고 싶습니당. 언니는 뭐하고 싶으심?

**Comment by seonghee2** [comment]
어???그러면 게임 알고리즘 제가 해도 될까염???:)

**Comment by seonghee2** [comment]
사실 2번이 엄청 하고 싶었는데 잘됐다!!

**Comment by fpdjsns** [comment]
seonghee2 - 게임 로직
fpdjsns - UI/UX

자세한 기획은 온라인이든 오프라인이든 회의 따로 하는걸로 합시다.

**Comment by fpdjsns** [comment]
이슈 종료합니다.
