### ISSUE TITLE
개발 일정 산정하기

### ISSUE THREAD

**Issue by fpdjsns** [veryear/2048#20]
이슈에 올라온 것 중 자신이 개발하는 것들은 언제까지 할 것인지 자기가 개발일정 산정해보는건 어떤가요?
협업인데 프로젝트의 대략적인 일정도 서로 좀 알아야 될 것 같고.
일정 산정해보면서 각자 일정 산정해보는 연습도 될 것 같은데.
모든 기능 이슈에 일정산정하지말고 다음에 개발할 이슈만 일정 산정하는걸로?
해당 이슈 기능 개발 다하면 다음에 개발할 것 개발 일정 산정하고 다시 개발에 들어가고 요렇게.
개발 일정은 시작 = 개발 시작, 종료 = PR 날리기 이 일정으로.

**Comment by seonghee2** [comment]
네 알겠습니다.

**Comment by fpdjsns** [comment]
그럼 첫 번째로 개발할 이슈에 각자 개발일정 산정 코맨트 달면 해당 이슈 종료하겠습니다.
달면 이 이슈에도 일정 산정 끝났다고 코멘트 달아주세요,

**Comment by fpdjsns** [comment]
https://github.com/veryear/2048/issues/8
개발 일정 산정했습니다.

**Comment by seonghee2** [comment]
네

**Comment by seonghee2** [comment]
근데 개발일정을 쓰는방법이 따로 있나요??

**Comment by fpdjsns** [comment]
그냥 알아보게만 쓰시면 될 것 같아요.

**Comment by seonghee2** [comment]
#17 
개발일정 산정했습니다.

**Comment by fpdjsns** [comment]
확인해서 해당 이슈 종료합니다.
앞으로는 알아서 개발 일정 산정해서 해당 이슈에 적어주세요~
