### ISSUE TITLE
code formatter 필요

### ISSUE THREAD

**Issue by fpdjsns** [veryear/2048#22]
코드 포매터가 필요할 것 같습니다.
포매터 정한다음에 저장이나 코드 푸시하기 전에 포매터 적용하고 하는걸로 하는게 어떤가요?
그래야 깃에서 충돌 별로 안 발생할 것 같습니다.

코드 포매터는 서로 찾아서 해당 이슈에 코멘트로 다는걸로 하죵.

# TODO
* [x] 코드 포매터 지정

**Comment by seonghee2** [comment]
네 좋습니다.
그런데 포매터는 어떤 형식으로 적용하나요?

**Comment by fpdjsns** [comment]
어떤 형식으로 적용한다는건 무슨 의미죵?
질문이 이해가 안가는데

**Comment by seonghee2** [comment]
포매터라는게 개발할때 폼을 정한다는 말 아닌가요???

**Comment by fpdjsns** [comment]
죄송한데 이해되게 예시 좀 들어주시겠나요??
https://m.blog.naver.com/withham1/221335872193
https://m.blog.naver.com/withham1/221326523236
이해하고있는 코드포매터가 위포스팅들에서 나오는 것과 같은거 맞나요??
어떤 형식..? 형식이 이해가 안가네요.
방법은 찾아봐야 할것같고요.

**Comment by fpdjsns** [comment]
이번주 주말 시간되시나요.
이번주까지 찾고 주말에 이야기하는거 어때요

**Comment by fpdjsns** [comment]
@seonghee2 이거나 대답좀..

**Comment by seonghee2** [comment]
죄송합니다.
메일 알람을 분명히 켜놨는데..
이번주 토일은 계열사 동기 캠핑이 있어서 만나지는 못할 것 같습니다.

**Comment by seonghee2** [comment]
뭔가 말로 정확히 설명은 안되지만 제가 찾아보고 이해한 포매터가 맞는 것 같습니다.
직접 사용자가 지정하지 않고, 제공되는 포메터를 사용할 수 있다는 건 처음 알았네요.
회의는 일요일에 하는 게 어떨까요?
갔다오고 파할때 연락하겠습니다.

**Comment by fpdjsns** [comment]
9/16(일) 에 이야기하는걸로 하겠습니다.
제 깃허브 책 들고 와주세용.
이 날 포매터 정하고 develop에 있는 코드 포매팅 한 번 싹 적용해 두는 걸로 합시당!

**Comment by seonghee2** [comment]
네!!아 2챕터 더 남았는데...주말에 후딱읽어야겠네염ㅠㅠ
예예

**Comment by fpdjsns** [comment]
9/15(토)로 변경.

**Comment by fpdjsns** [comment]
pycharm default 포매터 적용하기로 함.
develop에 포매터 적용한거 push 해 둠.

**Comment by fpdjsns** [comment]
이슈 종료합니다.
