### ISSUE TITLE
[UI/UX] moveBlock함수 파라미터 매개변수 추가

### ISSUE THREAD

**Issue by seonghee2** [veryear/2048#29]
* [x] 합쳐지는 값 매개변수로 추가해서 int로 받기
remark) 2048에서 4096(값제한 2048까지 둠)으로 합쳐지면 안되므로 int형으로 받기

**Comment by fpdjsns** [comment]
간단한거여서 이거먼저 하겠습니다.
개발일정 9/16(1D)
