### ISSUE TITLE
깃 관리 방법

### ISSUE THREAD

**Issue by fpdjsns** [veryear/2048#3]
Git flow 전략을 사용하면 괜찮을 것 같습니다.

브랜치
1. master : 제품 출시
2. feature : 기능 개발
3. release : 이번 출시 버전 준비
4. develop : 다음 출시 버전 준비
5. hotfix : 버그 수정

git flow 브랜치는 위와 같이 기본적으로 5가지를 사용하지만 알파환경도 없어서 release 브랜치까지 필요한가 싶네요.
좀 더 간단하게 가려면 release 없애고 master, feature, develop, hotfix 4개의 브랜치만 두는게 좋을 것 같은데 어떻게 생각하시나요?
feature 브랜치는 기존 전략과 같이 develop브랜치에서 따고요.

**Comment by fpdjsns** [comment]
test 입니다.

**Comment by fpdjsns** [comment]
develop 브랜치는 일단 생성해 두었습니다.

**Comment by fpdjsns** [comment]
음, 다시 생각해보니 release 브랜치 두고 기존 git flow 한 번 해보는 것도 괜춘할 듯.
release 브랜치에서 QA도 둘이서 자체적으로 한 번 해보고.

**Comment by seonghee2** [comment]
예. 감사합니다요~

**Comment by fpdjsns** [comment]
그러면 git-flow 따라서

develop에서 feature 브랜치 따기.
develop으로 feature 브랜치 머지
master로 가기 전에 develop(or feature) -> release 머지.
release에서 QA. QA에서 버그 발생 시 release에서 브랜치 따고 수정후 release로 머지.
QA끝나면 release -> master로 머지. & release -> develop으로 머지.
버그 발생시 master -> hotfix 브랜치 따기. 작업 후 hotfix -> master 머지.

이렇게 하는걸로.

**Comment by fpdjsns** [comment]
이슈 종료합니다.
