### ISSUE TITLE
[Algorithm] 값 랜덤하게 띄우기

### ISSUE THREAD

**Issue by seonghee2** [veryear/2048#33]
* [x] 화면에 2 랜덤하게 띄우기

**Comment by seonghee2** [comment]
이것 먼저하고 있습니다.
금일(09.25)까지 이 이슈 먼저 해결하고 #15 하고 pr 각각 날리겠습니다.
아직 알고리즘을 어떤식으로 구현해야 될지 잘 몰라서 시간 조금 걸릴 것 같지만
PR남겨놓겠습니다.

**Comment by fpdjsns** [comment]
close 해주세연

**Comment by fpdjsns** [comment]
그리고 다음 개발할 거 개발중 태그 ㄱㄱ
