### ISSUE TITLE
[기획] 게임 시작, 종료 화면

### ISSUE THREAD

**Issue by fpdjsns** [veryear/2048#38]
* [x] 게임 시작 화면
* [x] 게임 종료 화면
* [x] 게임 시작 시나리오 (접속 ~ 게임 시작까지
* [x] 게임 종료 시나리오 (게임 종료=game over ~ restart 까지)

날짜 잡고 기획 필요.

----
추가 (참조 : #13)
* [x] 블럭 생성 시 함수 설계

**Comment by fpdjsns** [comment]
@seonghee2 금요일 밤에 시간 괜찮으심?

**Comment by seonghee2** [comment]
네 시간됩니다.
집도착하면 연락할게욥!!

**Comment by fpdjsns** [comment]
회의안건 추가 : #13
블럭이 합쳐질 때 or 생성될 때 애니메이션을 추가할 까 하는데
이걸 어떻게 구분할지 (함수 인터페이스 계획 필요)

**Comment by seonghee2** [comment]
10월 09일에 회의 하겠습니다.

**Comment by seonghee2** [comment]
애니메이션 함수 추가 (3~5 프레임)
- 블록 이동
- 블록 합쳐지는 경우
- 랜덤함수로 새로운 블록 생성

**Comment by fpdjsns** [comment]
해당 이슈 다했으니까 종료해주세요.
다 끝난 기획이슈 제때종료부탁드립니다

**Comment by fpdjsns** [comment]
해당 이슈 다했으니까 종료해주세요.
다 끝난 기획이슈 제때종료부탁드립니다
@seonghee2
