### ISSUE TITLE
플랫폼 제약 없애기

### ISSUE THREAD

**Issue by fpdjsns** [veryear/2048#4]
개발은 일단 윈도우 프로그램으로 하되 나중에 홈페이지나 앱 용으로 확장할 수 있게 파일을 잘 나눠서 개발하면 좋을 것 같습니다.

**Comment by seonghee2** [comment]
넵넵!!

**Comment by fpdjsns** [comment]
해당 이슈에 대해서는 딱히 할 이야기가 없넹.
각자 개발할 때 최대한 모듈화해서 이식성 높이는 방향으로 개발하자.
해당 이슈 종료할게.
