### ISSUE TITLE
[Algorithm] 빈칸 검색하기

### ISSUE THREAD

**Issue by seonghee2** [veryear/2048#40]
* [x] : 4*4배열 검색해서 리스트에 좌표값 저장하기(함수)
* [x] : 해당 리스트 중 한곳에 랜던 값 넣기
~10.07

**Comment by fpdjsns** [comment]
태그 추가 ㄱ
이거 너무 작은 단위인데.. 결국 검색한다는게 랜덤 값 채워넣으려고 하는거니까.
해당 리스트 중 한 곳에 랜덤 값 넣는 것까지 이슈에 추가하자.
